// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * @title MockVerifier
 * @dev Mock ZK-SNARK verifier for testing purposes
 * 
 * This contract simulates a ZK-SNARK verifier for testing when the real
 * Verifier.sol (generated by snarkjs) is not available. It always returns
 * true for proof verification to allow testing of contract logic.
 * 
 * WARNING: This is for testing only and should NEVER be used in production.
 */
contract MockVerifier {
    /**
     * @dev Mock proof verification that always returns true
     * @param a First component of the proof (array of 2 uint256)
     * @param b Second component of the proof (2x2 matrix of uint256)
     * @param c Third component of the proof (array of 2 uint256)
     * @param input Public inputs (array of 1 uint256 for the commitment)
     * @return Always returns true for testing
     */
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[1] memory input
    ) public pure returns (bool) {
        // Silence unused parameter warnings by referencing them
        (a, b, c, input);
        
        // Always return true for testing purposes
        return true;
    }
}